
FROM php:8.1.11-alpine

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN apk add icu-dev
RUN docker-php-ext-configure intl && docker-php-ext-install intl

RUN docker-php-ext-install calendar
